import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { chromium, type Browser, type Page } from "playwright";
import { resetDatabase } from "../db/schema.js";
import { takeScreenshot } from "./screenshot.js";

let browser: Browser;
let page: Page;
let tmpDir: string;

const HTML = `<!DOCTYPE html><html><body style="background:#336699;width:1400px;height:900px"><h1 style="color:white">Test Page</h1></body></html>`;

beforeAll(async () => {
  browser = await chromium.launch({ headless: true });
  page = await browser.newPage();
  await page.setContent(HTML);
});

afterAll(async () => {
  await browser.close();
});

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), "browser-ss-test-"));
  process.env["BROWSER_DB_PATH"] = join(tmpDir, "test.db");
  process.env["BROWSER_DATA_DIR"] = tmpDir;
  resetDatabase();
});

afterEach(() => {
  resetDatabase();
  try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  delete process.env["BROWSER_DB_PATH"];
  delete process.env["BROWSER_DATA_DIR"];
});

describe("screenshot compression pipeline", () => {
  it("default format is webp", async () => {
    const result = await takeScreenshot(page, { track: false });
    expect(result.path.endsWith(".webp")).toBe(true);
  });

  it("compressed size is smaller than raw PNG size", async () => {
    const result = await takeScreenshot(page, { track: false });
    expect(result.original_size_bytes).toBeGreaterThan(0);
    expect(result.compressed_size_bytes).toBeGreaterThan(0);
    expect(result.compressed_size_bytes!).toBeLessThan(result.original_size_bytes!);
  });

  it("compression_ratio is between 0 and 1", async () => {
    const result = await takeScreenshot(page, { track: false });
    expect(result.compression_ratio).toBeGreaterThan(0);
    expect(result.compression_ratio!).toBeLessThan(1);
  });

  it("thumbnail is generated by default", async () => {
    const result = await takeScreenshot(page, { track: false });
    expect(result.thumbnail_path).toBeTruthy();
    expect(existsSync(result.thumbnail_path!)).toBe(true);
    expect(result.thumbnail_base64).toBeTruthy();
    expect(result.thumbnail_base64!.length).toBeGreaterThan(0);
  });

  it("thumbnail is ~200px wide or smaller", async () => {
    const result = await takeScreenshot(page, { track: false });
    // Thumbnail should be small base64
    const thumbBytes = Buffer.from(result.thumbnail_base64!, "base64").length;
    expect(thumbBytes).toBeLessThan(30000); // < 30KB for 200px thumb
  });

  it("maxWidth=640 downscales the image width", async () => {
    const result = await takeScreenshot(page, { maxWidth: 640, track: false });
    expect(result.width).toBeLessThanOrEqual(640);
  });

  it("compress=false skips compression pipeline, still works", async () => {
    const result = await takeScreenshot(page, { compress: false, track: false });
    expect(result.path).toBeTruthy();
    expect(result.base64.length).toBeGreaterThan(0);
  });

  it("format=jpeg produces jpeg output", async () => {
    const result = await takeScreenshot(page, { format: "jpeg", track: false });
    expect(result.path.endsWith(".jpeg")).toBe(true);
    expect(result.compressed_size_bytes!).toBeGreaterThan(0);
  });

  it("format=png produces png output", async () => {
    const result = await takeScreenshot(page, { format: "png", track: false });
    expect(result.path.endsWith(".png")).toBe(true);
  });

  it("base64 is valid and non-empty", async () => {
    const result = await takeScreenshot(page, { track: false });
    const buf = Buffer.from(result.base64, "base64");
    expect(buf.length).toBeGreaterThan(0);
    expect(buf.length).toBe(result.compressed_size_bytes ?? result.size_bytes);
  });

  it("track=true saves to gallery DB", async () => {
    const result = await takeScreenshot(page, { track: true });
    expect(result.gallery_id).toBeTruthy();
    const { getEntry } = await import("../db/gallery.js");
    const entry = getEntry(result.gallery_id!);
    expect(entry).toBeTruthy();
    expect(entry!.format).toBe("webp");
  });
});
